spring:
  application:
    name: devmentor-ai

  datasource:
    url: jdbc:postgresql://localhost:5434/devmentor
    username: devmentor
    password: devmentor123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:your-github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:your-github-client-secret}
            scope:
              - user:email
              - read:user
              - repo
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m

# AI Configuration
ai:
  # Claude (Anthropic) for chat/code review
  anthropic:
    api-key: ${ANTHROPIC_API_KEY:your-anthropic-api-key}
    model: claude-sonnet-4-20250514  # Claude Sonnet 4.5
    temperature: 0.3
    max-tokens: 8192

  # OpenAI for embeddings (Claude doesn't provide embedding models)
  openai:
    api-key: ${OPENAI_API_KEY:your-openai-api-key}

  embedding:
    model: text-embedding-3-small
    dimension: 1536

# Application Configuration
app:
  jwt:
    secret: ${JWT_SECRET:your-secret-key-change-in-production}
    expiration: 86400000 # 24 hours

  review:
    max-file-size: 10485760 # 10MB
    max-files-per-review: 100
    timeout: 300000 # 5 minutes

  github:
    api-url: https://api.github.com
    max-repo-size: 104857600 # 100MB

# GitHub OAuth Configuration (at root level)
github:
  oauth:
    client-id: ${GITHUB_CLIENT_ID:test-client-id}
    client-secret: ${GITHUB_CLIENT_SECRET:test-client-secret}

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Logging
logging:
  level:
    root: INFO
    com.devmentor: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/devmentor-ai.log

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true
