name: CD Pipeline

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t devmentor-ai:${{ github.sha }} .

      - name: Tag Docker image
        run: |
          docker tag devmentor-ai:${{ github.sha }} devmentor-ai:latest

      # Add your deployment steps here
      # Examples:
      # - Push to Docker Hub / AWS ECR / GCP Container Registry
      # - Deploy to Kubernetes
      # - Deploy to AWS ECS
      # - Deploy to Heroku

      - name: Deploy to production (placeholder)
        run: |
          echo "Deployment step would go here"
          echo "Image: devmentor-ai:${{ github.sha }}"

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
